fmt:
  image: registry.gitlab.com/webcloudpower/hetzner_cluster
  script:
    - tofu init
    - tofu fmt

validate:
  image: registry.gitlab.com/webcloudpower/hetzner_cluster
  script:
    - tofu init
    - tofu fmt

test:
  image: registry.gitlab.com/webcloudpower/hetzner_cluster
  script:
    - tofu init
    - tofu test 
