include:
  - template: Terraform/Base.latest.gitlab-ci.yml

stages:
  - validate

fmt:
  extends: .terraform:fmt

validate:
  extends: .terraform:validate

shell check:
  image: koalaman/shellcheck-alpine:stable
  stage: validate
  script:
    - shellcheck $(find . -name '*.sh')
