include:
  - component: gitlab.com/components/opentofu/job-templates@0.18.0-rc5
    inputs:
      version: 0.18.0-rc5
      opentofu_version: 1.6.2

stages: [validate]

fmt:
  extends: [.opentofu:fmt]
  image: registry.gitlab.com/webcloudpower/hetzner_cluster 
  stage: validate

validate:
  extends: [.opentofu:validate]
  image: registry.gitlab.com/webcloudpower/hetzner_cluster
  stage: validate

test:
  extends: [.opentofu:test]
  image: registry.gitlab.com/webcloudpower/hetzner_cluster
  stage: validate
